import faiss


index_path = r"F:\pyproject\Q9RAG\backend\scripts\vector_index.bin"

print(f"index path: {index_path}")

try:
    index = faiss.read_index(index_path)
    print(f"\033[32mFAISS index loaded successfully.\033[0m")
    print(f"dimension: {index.d}")
    print(f"vector count: {index.ntotal}")
except Exception as e:
    print(f"\033[31mFAISS index load failed: {str(e)[:200]}\033[0m")
    print("Please check whether the index file exists and was generated by faiss.write_index().")
